### ISSUE TITLE
Composer: depending on dev-master

### ISSUE THREAD

**Issue by dakur** [rostenkowski/translate#1]
In `composer.json`, there is hard dependency on `dev-master`.

```
"nette/neon": "dev-master",
"nette/safe-stream": "dev-master"
```

It should be dependent on a tag (even beta tag), not a developing branch, which is changing in time.

**Comment by stepansvoboda** [comment]
Should be fine now :) Thanks for reporting it.

**Comment by dakur** [comment]
Thank you. Do you plan to release it?

**Comment by stepansvoboda** [comment]
yup :)
